spring:
  application:
    name: ${APP_NAME:identity-service}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:120000}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:600000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:20000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  data:
    redis:
      #      url: ${REDIS_URL:}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:5000}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:2000}
      client-name: ${REDIS_CLIENT_NAME:${APP_NAME:identity-service}}
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:4}
          min-idle: ${REDIS_POOL_MIN_IDLE:1}
          max-wait: ${REDIS_POOL_MAX_WAIT:2000}
        shutdown-timeout: ${REDIS_SHUTDOWN_TIMEOUT:100}
  jwt:
    secret: ${JWT_SECRET:your-secret-key-min-256-bits-for-HS256-algorithm-security}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
  grpc:
    client:
      channels:
        user:
          address: "${USER_GRPC_HOST:localhost}:${USER_GRPC_PORT:9191}"
    server:
      port: ${GRPC_SERVER_PORT:9190}
server:
  port: ${SERVER_PORT:8090}
app:
  auth:
    cookie:
      secure: ${AUTH_COOKIE_SECURE:true}
      same-site: ${AUTH_COOKIE_SAME_SITE:None}
    google:
      client-ids: ${GOOGLE_CLIENT_IDS:}
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
      redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8090/api/auth/google/callback}
      success-redirect-url: ${GOOGLE_SUCCESS_REDIRECT_URL:https://cinema-star-ten.vercel.app/auth/callback}
      failure-redirect-url: ${GOOGLE_FAILURE_REDIRECT_URL:https://cinema-star-ten.vercel.app/login}
      state-ttl-minutes: ${GOOGLE_OAUTH_STATE_TTL_MINUTES:5}
