package com.cinema.Enum;

import lombok.Getter;

@Getter
public enum SuccessMessage {
    SUCCESS("Thao tác thành công"),
    CREATED("Tạo dữ liệu thành công"),
    UPDATED("Cập nhật dữ liệu thành công"),
    DELETED("Xóa dữ liệu thành công"),
    CANCELLED("Hủy thành công"),
    ACTIVATED("Kích hoạt thành công"),
    DEACTIVATED("Vô hiệu hóa thành công"),
    RECOVERED("Khôi phục thành công"),
    FETCHED("Lấy dữ liệu thành công"),
    SEARCHED("Tìm kiếm thành công"),
    LISTED("Danh sách dữ liệu được tải thành công"),
    UPLOADED("Tải lên thành công"),
    REGISTERED("Đăng ký thành công"),
    LOGGED_IN("Đăng nhập thành công"),
    LOGGED_OUT("Đăng xuất thành công"),
    TOKEN_REFRESHED("Làm mới token thành công"),
    OTP_VERIFIED("Xác thực OTP thành công"),
    OTP_RESENT("Gửi lại OTP thành công"),
    PASSWORD_RESET("Đặt lại mật khẩu thành công"),
    PASSWORD_CHANGED("Đổi mật khẩu thành công"),
    PROFILE_CREATED("Tạo hồ sơ thành công"),
    PROFILE_UPDATED("Cập nhật hồ sơ thành công"),
    PROFILE_DELETED("Xóa hồ sơ thành công"),
    PROFILE_RESTORED("Khôi phục hồ sơ thành công"),
    CINEMA_CREATED("Tạo rạp chiếu thành công"),
    CINEMA_UPDATED("Cập nhật rạp chiếu thành công"),
    CINEMA_STATUS_UPDATED("Cập nhật trạng thái rạp chiếu thành công"),
    CINEMA_DELETED("Xóa rạp chiếu thành công"),
    CINEMA_STAFF_ASSIGNED("Gán nhân sự rạp chiếu thành công"),
    CINEMA_STAFF_UPDATED("Cập nhật phân công nhân sự rạp chiếu thành công"),
    CINEMA_STAFF_UNASSIGNED("Bỏ gán nhân sự rạp chiếu thành công"),
    HALL_CREATED("Tạo phòng chiếu thành công"),
    HALL_UPDATED("Cập nhật phòng chiếu thành công"),
    HALL_DELETED("Xóa phòng chiếu thành công"),
    FILM_CREATED("Tạo phim thành công"),
    FILM_UPDATED("Cập nhật phim thành công"),
    FILM_DELETED("Xóa phim thành công"),
    BOOKING_CREATED("Tạo đặt vé thành công"),
    BOOKING_CANCELLED("Hủy đặt vé thành công"),
    PRODUCT_CREATED("Tạo sản phẩm thành công"),
    PRODUCT_UPDATED("Cập nhật sản phẩm thành công"),
    PRODUCT_DELETED("Xóa sản phẩm thành công"),
    PRODUCT_FETCHED("Lấy sản phẩm thành công"),
    PRODUCTS_SEARCHED("Tìm kiếm sản phẩm thành công"),
    PAYMENT_SESSION_CREATED("Tạo phiên thanh toán thành công"),
    PAYMENT_SESSION_COMPLETED("Hoàn tất phiên thanh toán thành công"),
    PAYMENT_REFUND_REQUESTED("Yêu cầu hoàn tiền thành công"),
    PROMOTION_CREATED("Tạo khuyến mãi thành công"),
    PROMOTION_UPDATED("Cập nhật khuyến mãi thành công"),
    PROMOTION_DELETED("Xóa khuyến mãi thành công"),
    PROMOTION_FETCHED("Lấy khuyến mãi thành công"),
    PROMOTIONS_SEARCHED("Tìm kiếm khuyến mãi thành công"),
    PRICING_POLICY_CREATED("Tạo chính sách giá thành công"),
    PRICING_POLICY_UPDATED("Cập nhật chính sách giá thành công"),
    PRICING_POLICY_DELETED("Xóa chính sách giá thành công"),
    PRICING_POLICY_FETCHED("Lấy chính sách giá thành công"),
    PRICING_POLICIES_SEARCHED("Tìm kiếm chính sách giá thành công"),
    SHOWTIME_CREATED("Tạo suất chiếu thành công"),
    SHOWTIME_UPDATED("Cập nhật suất chiếu thành công"),
    SHOWTIME_DELETED("Xóa suất chiếu thành công"),
    SHOWTIME_FETCHED("Lấy suất chiếu thành công"),
    SHOWTIMES_SEARCHED("Tìm kiếm suất chiếu thành công"),
    SEAT_SUGGESTIONS_FETCHED("Lấy gợi ý ghế thành công"),
    BOOKING_FETCHED("Lấy đặt vé thành công"),
    BOOKINGS_SEARCHED("Tìm kiếm đặt vé thành công"),
    BOOKING_CHECKOUT_CONTEXT_FETCHED("Lấy ngữ cảnh thanh toán thành công"),
    PAYMENT_SESSION_FETCHED("Lấy phiên thanh toán thành công"),
    PAYMENT_SESSIONS_SEARCHED("Tìm kiếm phiên thanh toán thành công"),
    CINEMA_REVENUE_REPORT_FETCHED("Lấy báo cáo doanh thu rạp thành công"),
    SHOWTIME_PERFORMANCE_REPORT_FETCHED("Lấy báo cáo hiệu suất suất chiếu thành công"),
    PROMOTION_PREVIEW_FETCHED("Lấy xem trước khuyến mãi thành công"),
    VIETQR_BANKS_FETCHED("Lấy danh sách ngân hàng VietQR thành công"),
    VIDEO_UPLOAD_SESSION_CREATED("Tạo phiên tải video thành công"),
    VIDEO_CHUNK_UPLOADED("Tải chunk video thành công"),
    VIDEO_UPLOAD_COMPLETED("Hoàn tất tải video thành công"),
    UPLOAD_IMAGES_COMPLETED("Tải ảnh lên thành công"),
    VIDEO_UPLOAD_STATUS_FETCHED("Lấy trạng thái tải video thành công"),
    HALL_LAYOUT_CREATED("Tạo bố cục phòng chiếu thành công"),
    HALL_LAYOUT_REPLACED("Cập nhật bố cục phòng chiếu thành công"),
    CINEMA_FETCHED("Lấy rạp chiếu thành công"),
    CINEMAS_SEARCHED("Tìm kiếm rạp chiếu thành công"),
    CINEMA_STAFFS_FETCHED("Lấy danh sách nhân sự rạp thành công"),
    HALL_FETCHED("Lấy phòng chiếu thành công"),
    HALLS_SEARCHED("Tìm kiếm phòng chiếu thành công"),
    FILM_FETCHED("Lấy phim thành công"),
    FILMS_SEARCHED("Tìm kiếm phim thành công"),
    FILMS_BATCH_FETCHED("Lấy danh sách phim theo lô thành công"),
    USER_CREATED("Tạo người dùng thành công"),
    USER_UPDATED("Cập nhật người dùng thành công"),
    USER_DELETED("Xóa người dùng thành công"),
    USER_RESTORED("Khôi phục người dùng thành công"),
    USER_FETCHED("Lấy người dùng thành công"),
    USERS_SEARCHED("Tìm kiếm người dùng thành công"),
    USER_EXISTENCE_CHECKED("Kiểm tra tồn tại người dùng thành công"),
    AUTH_OTP_SENT("Gửi OTP thành công"),
    AUTH_PASSWORD_RESET("Đặt lại mật khẩu thành công"),
    AUTH_PASSWORD_CHANGED("Đổi mật khẩu thành công"),
    AUTH_GOOGLE_LOGIN("Đăng nhập bằng Google thành công");

    private final String message;

    SuccessMessage(String message) {
        this.message = message;
    }
}
