spring:
  application:
    name: ${APP_NAME:film-service}
  mvc:
    trailing-slash:
      match: true
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:4}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:120000}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:600000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:20000}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  data:
    redis:
      #      url: ${REDIS_URL:}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT:5000}
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:4}
          min-idle: ${REDIS_POOL_MIN_IDLE:1}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1}
        shutdown-timeout: ${REDIS_SHUTDOWN_TIMEOUT:100}
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST}
#    port: ${SPRING_RABBITMQ_PORT}
#    username: ${SPRING_RABBITMQ_USERNAME}
#    password: ${SPRING_RABBITMQ_PASSWORD}
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9192}
server:
  port: ${SERVER_PORT:8092}
