services:
  identity-service:
    extends:
      file: compose.yaml
      service: identity-service
    profiles: ["docker-apps"]

  user-service:
    extends:
      file: compose.yaml
      service: user-service
    profiles: ["docker-apps"]

  film-service:
    extends:
      file: compose.yaml
      service: film-service
    profiles: ["docker-apps"]

  showtime-service:
    extends:
      file: compose.yaml
      service: showtime-service
    profiles: ["docker-apps"]

  hall-services:
    extends:
      file: compose.yaml
      service: hall-services
    profiles: ["docker-apps"]

  email-service:
    extends:
      file: compose.yaml
      service: email-service
    profiles: ["docker-apps"]

  postgres:
    extends:
      file: compose.yaml
      service: postgres

  redis:
    extends:
      file: compose.yaml
      service: redis

  rabbitmq:
    extends:
      file: compose.yaml
      service: rabbitmq

  envoy:
    extends:
      file: compose.yaml
      service: envoy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./envoy/envoy.dev.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/certs:/etc/envoy/certs:ro
    depends_on: []

volumes:
  pgdata:
  redis_data:
  rabbitmq_data:
