services:
  identity-service:
    profiles: ["docker-apps"]
  user-service:
    profiles: ["docker-apps"]
  film-service:
    profiles: ["docker-apps"]
  showtime-service:
    profiles: ["docker-apps"]
  email-service:
    profiles: ["docker-apps"]
  envoy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./envoy/envoy.dev.yaml:/etc/envoy/envoy.yaml:ro
    depends_on: []
