events {}

#      http {
#
#          upstream identity_service {
#              server identity-service:8090;
#          }
#
#          upstream user_service {
#              server user-service:8091;
#          }

    http {

        upstream identity_service {
            server host.docker.internal:8090;
        }

        upstream user_service {
            server host.docker.internal:8091;
        }

    server {
        listen 80;

        # ===== AUTH CHECK (FILTER TRƯỚC USER SERVICE) =====
        location = /auth-check {
            internal;
            proxy_pass http://identity_service/api/auth/auth-check;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host identity-service;
        }

        # ===== IDENTITY SERVICE (LOGIN, REGISTER, ...) =====
        location /api/auth/ {
            proxy_pass http://identity_service;
            proxy_set_header Host identity-service;
        }

       # ================================
       # 1. BỎ QUA AUTH CHO STAFFS
       # ================================

        location ^~ /api/users/customer/ {
              proxy_set_header Host user-service;
              limit_except GET {
                  proxy_pass http://user_service;
              }
         }

       location ^~ /api/users/manager/ {

           proxy_set_header Host user-service;

           # CHỈ GET mới chạy auth
           limit_except GET {
               proxy_pass http://user_service;
           }

           auth_request /auth-check;

           auth_request_set $user_id $upstream_http_x_user_id;
           auth_request_set $user_role $upstream_http_x_user_role;

           proxy_set_header X-User-ID $user_id;
           proxy_set_header X-User-Role $user_role;
           proxy_set_header Authorization $http_authorization;

           proxy_pass http://user_service;
       }


      location ^~ /api/users/staff/ {

          proxy_set_header Host user-service;

          # CHỈ GET mới chạy auth
          limit_except GET {
              proxy_pass http://user_service;
          }

          auth_request /auth-check;

          auth_request_set $user_id $upstream_http_x_user_id;
          auth_request_set $user_role $upstream_http_x_user_role;

          proxy_set_header X-User-ID $user_id;
          proxy_set_header X-User-Role $user_role;
          proxy_set_header Authorization $http_authorization;

          proxy_pass http://user_service;
        }

       # ================================
       # 3. TẤT CẢ API USERS KHÁC → AUTH CHECK
       # ================================
       location /api/users/ {
           auth_request /auth-check;

           # Nhận user info từ auth-service
           auth_request_set $user_id $upstream_http_x_user_id;
           auth_request_set $user_role $upstream_http_x_user_role;

           proxy_set_header X-User-ID $user_id;
           proxy_set_header X-User-Role $user_role;

           proxy_set_header Authorization $http_authorization;
           proxy_set_header Host user-service;

           proxy_pass http://user_service;
       }

        # ===== FALLBACK =====
        location / {
            return 404 "Not Found\n";
        }
    }
}
