syntax = "proto3";

package cinema.user.v1;

option java_multiple_files = true;
option java_package = "com.cinema.grpc.user";
option java_outer_classname = "UserInternalProto";

import "common.proto";

service UserInternalService {
  rpc CreateCustomerProfile(CreateCustomerProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc CreateManagerProfile(CreateManagerProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc CreateStaffProfile(CreateStaffProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc DeleteCustomerProfile(DeleteProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc DeleteCustomerProfileForBooking(DeleteCustomerProfileForBookingRequest) returns (cinema.common.v1.OperationReply);
  rpc DeleteManagerProfile(DeleteProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc DeleteStaffProfile(DeleteProfileRequest) returns (cinema.common.v1.OperationReply);
  rpc CheckUserExists(CheckUserExistsRequest) returns (CheckUserExistsReply);
  rpc AddUserLoyaltyPoints(AdjustUserLoyaltyPointsRequest) returns (AdjustUserLoyaltyPointsReply);
  rpc DeductUserLoyaltyPoints(AdjustUserLoyaltyPointsRequest) returns (AdjustUserLoyaltyPointsReply);
  rpc GetUserBasicById(GetUserBasicByIdRequest) returns (GetUserBasicByIdReply);
}

message CreateCustomerProfileRequest {
  string id = 1;
  string name = 2;
  string email = 3;
  string dob = 4;
  string gender = 5;
  string phone = 6;
  string role = 7;
}

message CreateManagerProfileRequest {
  string id = 1;
  string name = 2;
  string email = 3;
  string dob = 4;
  string gender = 5;
  string phone = 6;
  string role = 7;
  string bank_code = 8;
  string account_number = 9;
  string account_name = 10;
}

message CreateStaffProfileRequest {
  string id = 1;
  string name = 2;
  string email = 3;
  string dob = 4;
  string gender = 5;
  string phone = 6;
  string role = 7;
  string bank_code = 8;
  string account_number = 9;
  string account_name = 10;
}

message CheckUserExistsRequest {
  string user_id = 1;
}

message DeleteProfileRequest {
  string user_id = 1;
  string actor_id = 2;
  string actor_role = 3;
}

message DeleteCustomerProfileForBookingRequest {
  string user_id = 1;
}

message CheckUserExistsReply {
  bool success = 1;
  string error_key = 2;
  string message = 3;
  bool exists = 4;
}

message GetUserBasicByIdRequest {
  string user_id = 1;
}

message AdjustUserLoyaltyPointsRequest {
  string user_id = 1;
  int64 loyalty_points = 2;
}

message AdjustUserLoyaltyPointsReply {
  bool success = 1;
  string error_key = 2;
  string message = 3;
  int64 loyalty_points = 4;
}

message UserBasicPayload {
  string id = 1;
  string name = 2;
  int64 loyalty_points = 3;
}

message GetUserBasicByIdReply {
  bool success = 1;
  string error_key = 2;
  string message = 3;
  UserBasicPayload user = 4;
}
